# -*- coding: utf-8 -*-
"""Policy-based medical safety guardrails.

Six policies:
1. No PHI leakage.
2. No definitive diagnosis claims.
3. No direct treatment orders or prescriptions.
4. Imaging must be framed as auxiliary/non-diagnostic.
5. Evidence level / uncertainty must be disclosed.
6. High-risk anatomy and urgent safety flags must be highlighted.
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import List, Dict, Any


GLOBAL_DISCLAIMER = (
    "\n---\n"
    "⚠️ FOR CLINICIAN REVIEW ONLY — DECISION SUPPORT, NOT A DECISION. "
    "This output is generated by a research prototype and is NOT validated for clinical use. "
    "It does not replace the judgement of a neurosurgeon, pediatric oncologist, radiologist, "
    "or the multidisciplinary team (MDT). All recommendations require independent clinical verification.\n"
    "⚠️ 僅供臨床醫師參考 — 決策支援，非決策本身。本輸出由研究原型產生，未經臨床驗證，"
    "不取代神經外科、兒童腫瘤科、放射科或 MDT 的判斷。所有建議須經獨立臨床查證。\n"
)


@dataclass
class GuardrailResult:
    passed: bool
    blocked: List[str] = field(default_factory=list)
    flagged: List[str] = field(default_factory=list)
    annotations: List[str] = field(default_factory=list)
    safe_text: str = ""


class MedicalGuardrails:
    def __init__(self) -> None:
        self.phi_patterns = [
            ("MRN", re.compile(r"\bMRN[:\s]*[A-Za-z0-9_-]+", re.I)),
            ("email", re.compile(r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}")),
            ("phone", re.compile(r"\b(?:\+?\d{1,3}[-.\s]?)?(?:\(?\d{2,4}\)?[-.\s]?)?\d{3,4}[-.\s]?\d{4}\b")),
        ]
        self.definitive_terms = [
            "definitive diagnosis", "certainly", "確定診斷", "必然是", "confirmed diagnosis",
        ]
        self.order_terms = [
            "start chemotherapy", "prescribe", "administer", "開立", "立即給予", "處方",
        ]
        self.high_risk_terms = [
            "basilar artery", "brainstem", "pons", "midbrain", "medulla", "cranial nerve", "hydrocephalus",
            "fourth ventricle", "spinal cord",
        ]

    def check(self, text: str) -> GuardrailResult:
        text = text or ""
        blocked = []
        flagged = []
        annotations = []
        safe_text = text

        # Policy 1: PHI
        for label, pat in self.phi_patterns:
            if pat.search(safe_text):
                blocked.append(f"Policy 1: potential PHI pattern detected ({label})")
                safe_text = pat.sub("[REDACTED]", safe_text)

        # Policy 2: definitive diagnosis language
        if any(term.lower() in safe_text.lower() for term in self.definitive_terms):
            annotations.append("Policy 2: definitive diagnostic wording detected; interpret as differential/working impression only.")
            safe_text += "\n\nGuardrail note: Diagnostic statements must be treated as working differential impressions pending clinician verification."

        # Policy 3: direct treatment orders
        if any(term.lower() in safe_text.lower() for term in self.order_terms):
            annotations.append("Policy 3: treatment-order wording detected; converted to MDT discussion framing.")
            safe_text += "\n\nGuardrail note: Therapy language is not a prescription; it is a discussion prompt for MDT review."

        # Policy 4: imaging disclaimer
        if "imaging" in safe_text.lower() or "影像" in safe_text:
            if "AI 影像輔助" not in safe_text and "non-diagnostic" not in safe_text.lower():
                annotations.append("Policy 4: imaging disclaimer auto-added.")
                safe_text += "\n\nAI 影像輔助觀察，最終判讀須由放射科/神經外科醫師負責；不可作為確定性診斷依據。"

        # Policy 5: uncertainty/evidence
        if "evidence" not in safe_text.lower() and "證據" not in safe_text:
            annotations.append("Policy 5: missing disclosure of evidence level/confidence (auto-annotated).")
            safe_text += "\n\nEvidence note: Evidence levels and confidence are preliminary and require clinician verification."

        # Policy 6: high-risk anatomy flags
        for term in self.high_risk_terms:
            if term.lower() in safe_text.lower():
                flagged.append(term)
        if flagged:
            safe_text += "\n\nHigh-risk anatomy flagged by guardrail: " + ", ".join(sorted(set(flagged))) + "."

        if GLOBAL_DISCLAIMER.strip() not in safe_text:
            safe_text += GLOBAL_DISCLAIMER

        return GuardrailResult(
            passed=len(blocked) == 0,
            blocked=blocked,
            flagged=sorted(set(flagged)),
            annotations=annotations,
            safe_text=safe_text,
        )


# Backward-compatible alias
Guardrails = MedicalGuardrails
